services:
  - type: web
    name: mirrora-cron-job
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_handler.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GRIDHUB_PRIVATE_KEY_PATH
        sync: false
      - key: REPO_NAME
        sync: false
      - key: LOG_PATH
        sync: false
      - key: NOTION_SECRET
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
